#!/bin/bash
rm result.zip 2>/dev/null
mkdir .temp 2>/dev/null
python py/js script.js > .temp/script.js
python py/html index.html > .temp/index.html 
zip -j result.zip .temp/* &>/dev/null
rm -rf .temp
size=$(stat -c '%s' result.zip)
echo "$size bytes of 13312: "$((size*100/13312))'%'
